# BSD 2-CLAUSE LICENSE

# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:

# Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
# Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# #ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# Original author: Reza Hosseini


from abvelocity.journey.event.gen_event_query import EventTable, gen_event_query


def gen_event_tables_query(
    event_tables: list[EventTable], start_date: str, end_date: str, create_table_prefix: str
) -> list[str]:
    """
    Generates a list of queries, each extracting one type of event in the signup flow.

    Args:
        event_tables (list[EventTable]): List of EventTable instances representing event table configurations.
        start_date (str): The start date for filtering records (format: 'YYYY-MM-DD-00').
        end_date (str): The end date for filtering records (format: 'YYYY-MM-DD-00').
        create_table_prefix (str): Prefix for creating new tables.

    Returns:
        list[str]: A list of generated SQL queries.
    """
    query_list = []
    for event_table in event_tables:
        query = gen_event_query(
            event_table=event_table,
            start_date=start_date,
            end_date=end_date,
            create_table_prefix=create_table_prefix,
        )
        query_list.append(query)
    return query_list


def union_tables_query(
    event_tables: list[EventTable], create_table_prefix: str, order_by: str = ""
) -> str:
    """This is a simple union (concatenating rows of tables with the same columns).
    These tables are generated by `gen_tables_query`, and each tracks one material action in the target flow.
    The name of the final table will be `f"{create_table_prefix}_union"`.

    Args:
        event_tables (list[EventTable]): List of EventTable instances for union operations.
        create_table_prefix (str): Prefix for the table creation.
        order_by (str, optional): ORDER BY clause to sort the results. Defaults to "".

    Returns:
        str: A complete SQL query to create a union of all tables.
    """
    query_list = []

    # Build SELECT queries for each table
    for event_table in event_tables:
        query_list.append(
            f"""
            SELECT * FROM {event_table.output_table_name}
        """
        )

    union_table_name = f"{create_table_prefix}_union"
    print(f"Generated table name will be: {union_table_name}")

    query = f"""
        DROP TABLE IF EXISTS {union_table_name};
        CREATE TABLE IF NOT EXISTS {union_table_name} AS
    """

    # Join the queries with UNION ALL
    query += """
        UNION ALL
    """.join(
        query_list
    )

    # Append the ORDER BY clause if provided
    if order_by:
        query += f" ORDER BY {order_by}"

    return query
